---
latitude: 40.7591257
longitude: -73.9859554
map_zoom: 5
name: OYO Times Square
email: info@oyotimessquare.com
phone_number: 123-123-1234
address:
  street1: 157 West 47th Street
  state: New York
  city: NY
  zip_code: '10036'
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCGTS
_portal_id: gateshoteltimessquare
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  reservations_email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  google_location:
    type: location
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
get_directions_url: https://goo.gl/maps/d9c5eEciAtAALBGd6
map_url: https://goo.gl/maps/foYYsnBTTn8WBoFK6
logo:
  name: oyo-timessquare-logo
  content_type: image/svg+xml
  date_added: 2019-10-22-052948
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  resource_type: raw
  size: 3476
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  file_size: 
  alt: OYO Times Square
  caption: ''
  description: ''
logo_secondary:
  name: oyo-timessquare-logo
  content_type: image/svg+xml
  date_added: 2019-10-22-052948
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  resource_type: raw
  size: 3476
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1571736588/rtctv0u7lvpcoo9xdqlu.svg"
  file_size: 
  alt: OYO Times Square
  caption: ''
  description: ''
phone: 212.768.3700
reservations_email: reservations@oyotimessquare.com
