---
latitude: 40.7591257
longitude: -73.9859554
map_zoom: 5
name: OYO Times Square
email: info@oyotimessquare.com
phone_number: 123-123-1234
address:
  street1: 157 West 47th Street
  state: New York
  city: NY
  zip_code: '10036'
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCGTS
_portal_id: gateshoteltimessquare
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  email:
    type: string
  reservations_email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  google_location:
    type: location
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
get_directions_url: https://goo.gl/maps/d9c5eEciAtAALBGd6
map_url: https://goo.gl/maps/foYYsnBTTn8WBoFK6
logo:
  name: TGHTS-Logo
  content_type: image/png
  date_added: 2019-09-09-090135
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1568034095/eo63vxrlykmamnlnlz35.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1568034095/eo63vxrlykmamnlnlz35.png"
  width: 1920
  height: 1057
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1568034095/eo63vxrlykmamnlnlz35.png"
  resource_type: image
  size: 117723
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1568034095/eo63vxrlykmamnlnlz35.png"
  file_size: 
  alt: OYO Times Square
  caption: ''
  description: ''
logo_secondary:
  name: TGHTS-Logo
  content_type: image/png
  date_added: 2019-09-09-090135
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1568034095/eo63vxrlykmamnlnlz35.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1568034095/eo63vxrlykmamnlnlz35.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1568034095/eo63vxrlykmamnlnlz35.png"
  width: 1920
  height: 1057
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1568034095/eo63vxrlykmamnlnlz35.png"
  resource_type: image
  size: 117723
  git_file_name: _assets/image_data/TGHTS-Logo.png.json
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1568034095/eo63vxrlykmamnlnlz35.png"
  file_size: 
  alt: OYO Times Square
  caption: ''
  description: ''
phone: 212.768.3700
reservations_email: reservations@oyotimessquare.com
